language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  # Install the packages in requirements.txt first, to pick up the direct
  # github links.
  - pip install -r requirements.txt
  # Install the jet_tracking module
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest jet_tracking/tests
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  # Flake8 will only be a warning for now:
  - flake8 --max-line-length=115 || /bin/true
  - make -C docs html  # Build the documentation.
